"""Country gazetteer for news attribution (v46).

Generated once from the `COUNTRIES` array in index.html (the canonical country
list) intersected with the ISO codes that actually appear in
data/commodity_flows.json. Countries absent from the trade graph are omitted:
if we cannot place a country on a corridor, naming it in a headline buys the
reader nothing.

PURE DATA — no I/O, no imports. Same contract as _news_taxonomy.py.

WHY A CURATED GAZETTEER AND NOT AN NLP LIBRARY:
  Country attribution from a headline is MODELED, not measured, and the
  failure mode is silent and embarrassing: "Turkey" the bird, "Georgia" the
  US state, "Chad" and "Jordan" the given names, "China" the porcelain. A
  dependency-free table with explicit ambiguity guards is auditable by anyone
  reading this file; a black-box NER model is not, and this project's whole
  claim is that its inputs can be checked.

  Every attribution produced from this table must be badged `modeled` in the
  output. It is a keyword match, and it should never be presented as though a
  human or a wire service assigned the country.
"""

# ISO3 -> display name. 184 entries, all present in the trade graph.
COUNTRY_NAMES = {
    "AFG":  "Afghanistan",
    "AGO":  "Angola",
    "ALB":  "Albania",
    "ARE":  "UAE",
    "ARG":  "Argentina",
    "ARM":  "Armenia",
    "AUS":  "Australia",
    "AUT":  "Austria",
    "AZE":  "Azerbaijan",
    "BDI":  "Burundi",
    "BEL":  "Belgium",
    "BEN":  "Benin",
    "BFA":  "Burkina Faso",
    "BGD":  "Bangladesh",
    "BGR":  "Bulgaria",
    "BHR":  "Bahrain",
    "BIH":  "Bosnia & Herzegovina",
    "BLR":  "Belarus",
    "BLZ":  "Belize",
    "BOL":  "Bolivia",
    "BRA":  "Brazil",
    "BRB":  "Barbados",
    "BRN":  "Brunei",
    "BTN":  "Bhutan",
    "BWA":  "Botswana",
    "CAF":  "Central African Rep.",
    "CAN":  "Canada",
    "CHE":  "Switzerland",
    "CHL":  "Chile",
    "CHN":  "China",
    "CIV":  "Ivory Coast",
    "CMR":  "Cameroon",
    "COD":  "DR Congo",
    "COG":  "Republic of Congo",
    "COL":  "Colombia",
    "COM":  "Comoros",
    "CPV":  "Cape Verde",
    "CRI":  "Costa Rica",
    "CUB":  "Cuba",
    "CYP":  "Cyprus",
    "CZE":  "Czech Republic",
    "DEU":  "Germany",
    "DJI":  "Djibouti",
    "DMA":  "Dominica",
    "DNK":  "Denmark",
    "DOM":  "Dominican Republic",
    "DZA":  "Algeria",
    "ECU":  "Ecuador",
    "EGY":  "Egypt",
    "ERI":  "Eritrea",
    "ESP":  "Spain",
    "EST":  "Estonia",
    "ETH":  "Ethiopia",
    "FIN":  "Finland",
    "FJI":  "Fiji",
    "FRA":  "France",
    "GAB":  "Gabon",
    "GBR":  "United Kingdom",
    "GEO":  "Georgia",
    "GHA":  "Ghana",
    "GIN":  "Guinea",
    "GMB":  "Gambia",
    "GNB":  "Guinea-Bissau",
    "GNQ":  "Equatorial Guinea",
    "GRC":  "Greece",
    "GRD":  "Grenada",
    "GRL":  "Greenland",
    "GTM":  "Guatemala",
    "GUY":  "Guyana",
    "HKG":  "Hong Kong",
    "HND":  "Honduras",
    "HRV":  "Croatia",
    "HTI":  "Haiti",
    "HUN":  "Hungary",
    "IDN":  "Indonesia",
    "IND":  "India",
    "IRL":  "Ireland",
    "IRN":  "Iran",
    "IRQ":  "Iraq",
    "ISL":  "Iceland",
    "ISR":  "Israel",
    "ITA":  "Italy",
    "JAM":  "Jamaica",
    "JOR":  "Jordan",
    "JPN":  "Japan",
    "KAZ":  "Kazakhstan",
    "KEN":  "Kenya",
    "KGZ":  "Kyrgyzstan",
    "KHM":  "Cambodia",
    "KOR":  "South Korea",
    "KWT":  "Kuwait",
    "LAO":  "Laos",
    "LBN":  "Lebanon",
    "LBR":  "Liberia",
    "LBY":  "Libya",
    "LCA":  "Saint Lucia",
    "LKA":  "Sri Lanka",
    "LSO":  "Lesotho",
    "LTU":  "Lithuania",
    "LUX":  "Luxembourg",
    "LVA":  "Latvia",
    "MAC":  "Macao",
    "MAR":  "Morocco",
    "MDA":  "Moldova",
    "MDG":  "Madagascar",
    "MDV":  "Maldives",
    "MEX":  "Mexico",
    "MKD":  "North Macedonia",
    "MLI":  "Mali",
    "MLT":  "Malta",
    "MMR":  "Myanmar",
    "MNE":  "Montenegro",
    "MNG":  "Mongolia",
    "MOZ":  "Mozambique",
    "MRT":  "Mauritania",
    "MUS":  "Mauritius",
    "MWI":  "Malawi",
    "MYS":  "Malaysia",
    "NAM":  "Namibia",
    "NER":  "Niger",
    "NGA":  "Nigeria",
    "NIC":  "Nicaragua",
    "NLD":  "Netherlands",
    "NOR":  "Norway",
    "NPL":  "Nepal",
    "NRU":  "Nauru",
    "NZL":  "New Zealand",
    "OMN":  "Oman",
    "PAK":  "Pakistan",
    "PAN":  "Panama",
    "PER":  "Peru",
    "PHL":  "Philippines",
    "PNG":  "Papua New Guinea",
    "POL":  "Poland",
    "PRK":  "North Korea",
    "PRT":  "Portugal",
    "PRY":  "Paraguay",
    "PSE":  "Palestine",
    "QAT":  "Qatar",
    "ROU":  "Romania",
    "RUS":  "Russia",
    "RWA":  "Rwanda",
    "SAU":  "Saudi Arabia",
    "SDN":  "Sudan",
    "SEN":  "Senegal",
    "SGP":  "Singapore",
    "SLB":  "Solomon Islands",
    "SLE":  "Sierra Leone",
    "SLV":  "El Salvador",
    "SOM":  "Somalia",
    "SRB":  "Serbia",
    "SSD":  "South Sudan",
    "STP":  "S\u00e3o Tom\u00e9 & Pr\u00edncipe",
    "SUR":  "Suriname",
    "SVK":  "Slovakia",
    "SVN":  "Slovenia",
    "SWE":  "Sweden",
    "SWZ":  "Eswatini",
    "SYC":  "Seychelles",
    "SYR":  "Syria",
    "TCD":  "Chad",
    "TGO":  "Togo",
    "THA":  "Thailand",
    "TJK":  "Tajikistan",
    "TKM":  "Turkmenistan",
    "TLS":  "Timor-Leste",
    "TTO":  "Trinidad & Tobago",
    "TUN":  "Tunisia",
    "TUR":  "Turkey",
    "TWN":  "Taiwan",
    "TZA":  "Tanzania",
    "UGA":  "Uganda",
    "UKR":  "Ukraine",
    "URY":  "Uruguay",
    "USA":  "United States",
    "UZB":  "Uzbekistan",
    "VCT":  "Saint Vincent and the Grenadines",
    "VEN":  "Venezuela",
    "VNM":  "Vietnam",
    "VUT":  "Vanuatu",
    "YEM":  "Yemen",
    "ZAF":  "South Africa",
    "ZMB":  "Zambia",
    "ZWE":  "Zimbabwe",
}

# Demonyms and common alternate surface forms -> ISO3.
# Matched case-insensitively on word boundaries, same as COUNTRY_NAMES.
ALIASES = {
    "russian": "RUS", "russia's": "RUS",
    "ukrainian": "UKR", "ukraine's": "UKR",
    # NOTE: bare "us" is deliberately NOT an alias. It is the English pronoun,
    # and \b matching does not help — "what this costs us" is not a US story.
    # "u.s." / "u.k." are handled in DOTTED_FORMS below, NOT here: a trailing
    # "." means the \b at the end of the pattern can never match, so these
    # were dead entries and wire-style "U.S. warns..." headlines silently lost
    # their country attribution.
    "american": "USA", "usa": "USA",
    "united states": "USA", "washington": "USA",
    "chinese": "CHN", "beijing": "CHN",
    "indian": "IND", "new delhi": "IND",
    "brazilian": "BRA", "brasilia": "BRA",
    "argentine": "ARG", "argentinian": "ARG", "buenos aires": "ARG",
    "australian": "AUS", "canberra": "AUS",
    "canadian": "CAN", "ottawa": "CAN",
    "egyptian": "EGY", "cairo": "EGY",
    "indonesian": "IDN", "jakarta": "IDN",
    "malaysian": "MYS", "kuala lumpur": "MYS",
    "vietnamese": "VNM", "hanoi": "VNM",
    "thai": "THA", "bangkok": "THA",
    "turkish": "TUR", "ankara": "TUR", "turkiye": "TUR", "türkiye": "TUR",
    "pakistani": "PAK", "islamabad": "PAK",
    "bangladeshi": "BGD", "dhaka": "BGD",
    "nigerian": "NGA", "abuja": "NGA",
    "ethiopian": "ETH", "addis ababa": "ETH",
    "kenyan": "KEN", "nairobi": "KEN",
    "saudi": "SAU", "riyadh": "SAU", "saudi arabian": "SAU",
    "iranian": "IRN", "tehran": "IRN",
    "iraqi": "IRQ", "baghdad": "IRQ",
    "syrian": "SYR", "damascus": "SYR",
    "yemeni": "YEM", "sanaa": "YEM",
    "sudanese": "SDN", "khartoum": "SDN",
    "japanese": "JPN", "tokyo": "JPN",
    # "korean" alone is ambiguous between KOR and PRK, so it is guarded below
    # rather than resolved blind; "south korean"/"seoul" are unambiguous.
    "korean": "KOR", "seoul": "KOR", "south korean": "KOR",
    "north korean": "PRK", "pyongyang": "PRK",
    "filipino": "PHL", "philippine": "PHL", "manila": "PHL",
    "mexican": "MEX", "mexico city": "MEX",
    "french": "FRA", "paris": "FRA",
    "german": "DEU", "berlin": "DEU",
    "spanish": "ESP", "madrid": "ESP",
    "italian": "ITA", "rome": "ITA",
    "dutch": "NLD", "netherlands": "NLD", "amsterdam": "NLD",
    "polish": "POL", "warsaw": "POL",
    "romanian": "ROU", "bucharest": "ROU",
    "kazakh": "KAZ", "astana": "KAZ", "kazakhstani": "KAZ",
    "moroccan": "MAR", "rabat": "MAR",
    "algerian": "DZA", "algiers": "DZA",
    "tunisian": "TUN", "tunis": "TUN",
    "peruvian": "PER", "lima": "PER",
    "colombian": "COL", "bogota": "COL",
    "chilean": "CHL", "santiago": "CHL",
    "uruguayan": "URY", "paraguayan": "PRY",
    "british": "GBR", "uk": "GBR", "london": "GBR",
    "united kingdom": "GBR", "britain": "GBR",
    "afghan": "AFG", "kabul": "AFG",
    "somali": "SOM", "mogadishu": "SOM",
    "haitian": "HTI", "venezuelan": "VEN",
    "ivorian": "CIV", "ivory coast": "CIV", "cote d'ivoire": "CIV",
    "ghanaian": "GHA", "senegalese": "SEN",
    "myanmar": "MMR", "burmese": "MMR",
    "emirati": "ARE", "dubai": "ARE", "abu dhabi": "ARE",
}

# Multi-country shorthand that reporters actually use. Expanded to every
# member, because a "Black Sea" disruption is a corridor event and the whole
# point of this page is corridors.
REGIONS = {
    "black sea": ["RUS", "UKR"],
    "horn of africa": ["ETH", "SOM", "ERI", "DJI", "KEN"],
    "sahel": ["MLI", "NER", "BFA", "TCD", "MRT"],
    "southeast asia": ["IDN", "MYS", "THA", "VNM", "PHL"],
    "north africa": ["EGY", "DZA", "MAR", "TUN", "LBY"],
    "west africa": ["NGA", "GHA", "CIV", "SEN", "BFA"],
    "east africa": ["ETH", "KEN", "TZA", "UGA", "SOM"],
    "gulf states": ["SAU", "ARE", "QAT", "KWT", "OMN", "BHR"],
    "south america": ["BRA", "ARG", "URY", "PRY", "CHL", "PER", "COL"],
}

# Surface forms that are country names but are USUALLY something else.
# A match is only accepted when one of the guard terms also appears in the
# headline. Without this, every Thanksgiving story attributes to Turkey and
# every porcelain story to China.
AMBIGUOUS = {
    # Resolves to South Korea only when nothing marks it as the North.
    "korean": ["south korea", "seoul", "south korean"],
    "turkey": ["export", "import", "wheat", "grain", "ban", "tariff", "ankara",
               "lira", "istanbul", "trade", "harvest", "crop", "mill"],
    "china": ["export", "import", "soybean", "trade", "tariff", "beijing",
              "purchase", "cargo", "demand", "customs", "yuan", "crop"],
    "georgia": ["tbilisi", "caucasus", "black sea", "georgian"],
    "jordan": ["amman", "import", "wheat", "tender", "kingdom", "barley"],
    "chad": ["n'djamena", "sahel", "lake chad", "famine", "drought"],
    "niger": ["niamey", "sahel", "junta", "drought", "famine"],
    "guinea": ["conakry", "bauxite", "west africa"],
    "mali": ["bamako", "sahel", "junta"],
    "oman": ["muscat", "gulf", "import"],
    "chile": ["santiago", "copper", "export", "harvest"],
    "india": ["export", "import", "rice", "wheat", "sugar", "onion", "tariff",
              "delhi", "monsoon", "crop", "ban", "mandi"],
}

# Region/aggregate codes that are not sovereign states. Never emitted as an
# exposed country; used only to recognise EU-level reporting.
NON_SOVEREIGN = {"EU"}

# Abbreviations ending in a period. These CANNOT go in ALIASES because the
# matcher anchors with \b, and a trailing "." leaves no word character on
# either side of the final boundary, so the pattern never matches. Matched
# with an explicit leading boundary and no trailing one.
DOTTED_FORMS = {
    "u.s.": "USA",
    "u.k.": "GBR",
    "u.a.e.": "ARE",
}
