#!/usr/bin/env python3
"""Keep the per-page heads in one place.

seo.json (repo root) is the source of truth for page titles and descriptions:
  - middleware.js imports it and writes the <head> tags every page path is served with;
  - this script copies its tab table into TAB_SEO in index.html (used by updatePageTitle
    while the reader moves between tabs) and refills seo.json's `countries` (ISO -> name,
    from the COUNTRIES array in index.html) and `commodities` (slug -> name, from
    COMMODITY_META), which the middleware needs to title /countryflows/<slug> and
    /commodities/<crop>.

    python3 scripts/build_seo.py          # write
    python3 scripts/build_seo.py --check  # exit 1 if seo.json or index.html is out of date

Hand-run after editing seo.json or adding a country or crop to index.html.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEO = ROOT / 'seo.json'
HTML = ROOT / 'index.html'
BEGIN = '/* TAB_SEO:BEGIN generated by scripts/build_seo.py from seo.json; edit seo.json, not these lines */'
END = '/* TAB_SEO:END */'
MAX_DESC = 155


def countries(html: str) -> dict:
    start = html.index('const COUNTRIES = [')
    end = html.index('window.COUNTRIES = COUNTRIES;', start)
    out = {}
    for iso, name in re.findall(r'\biso:"([A-Z]{2,3}(?:-[A-Z]{2})?)",name:"([^"]+)"', html[start:end]):
        out.setdefault(iso, name)
    return dict(sorted(out.items()))


def commodities(html: str) -> dict:
    start = html.index('const COMMODITY_META = [')
    end = html.index('];', start)
    return {dk: key for key, dk in re.findall(r'\{ key:"([^"]+)", dataKey:"([^"]+)"', html[start:end])}


def tab_block(tabs: dict) -> str:
    rows, aliases = [], []
    for tab, t in tabs.items():
        if 'same_as' in t:
            aliases.append(f"TAB_SEO.{tab} = TAB_SEO.{t['same_as']};")
            continue
        rows.append(f"  {tab}: [{json.dumps(t['title'], ensure_ascii=False)}, {json.dumps(t['description'], ensure_ascii=False)}],")
    return '\n'.join([BEGIN, 'const TAB_SEO = {', *rows, '};', *aliases, END])


def check(seo: dict) -> list[str]:
    errs = []
    for tab, t in seo['tabs'].items():
        if 'same_as' in t:
            continue
        if len(t['description']) > MAX_DESC:
            errs.append(f'tabs.{tab}: description {len(t["description"])} chars > {MAX_DESC}')
    for kind, names in (('country', seo['countries']), ('commodity', seo['commodities'])):
        for name in names.values():
            d = seo[kind]['description'].replace('{name}', name)
            if len(d) > MAX_DESC:
                errs.append(f'{kind} {name}: description {len(d)} chars > {MAX_DESC}')
    return errs


def main() -> int:
    only_check = '--check' in sys.argv
    html = HTML.read_text(encoding='utf-8')
    seo = json.loads(SEO.read_text(encoding='utf-8'))
    seo['countries'] = countries(html)
    seo['commodities'] = commodities(html)
    errs = check(seo)
    for e in errs:
        print('ERROR', e)

    block = tab_block(seo['tabs'])
    if BEGIN in html:
        a = html.index(BEGIN)
        b = html.index(END, a) + len(END)
    else:  # first run: replace the hand-written table and its alias line
        a = html.index('const TAB_SEO = {')
        alias = 'TAB_SEO.about = TAB_SEO.methodology;'
        b = html.index(alias, a) + len(alias)
    new_html = html[:a] + block + html[b:]
    new_seo = json.dumps(seo, ensure_ascii=False, indent=2) + '\n'

    stale = [p.name for p, old, new in ((HTML, html, new_html), (SEO, SEO.read_text(encoding='utf-8'), new_seo)) if old != new]
    if only_check:
        if stale:
            print('out of date:', ', '.join(stale), '(run python3 scripts/build_seo.py)')
        return 1 if (stale or errs) else 0
    HTML.write_text(new_html, encoding='utf-8')
    SEO.write_text(new_seo, encoding='utf-8')
    print(f"tabs {len(seo['tabs'])}, countries {len(seo['countries'])}, commodities {len(seo['commodities'])}; wrote {', '.join(stale) or 'nothing'}")
    return 1 if errs else 0


if __name__ == '__main__':
    sys.exit(main())
